name: GitHub Actions
run-name: ${{ github.actor }} runs GitHub actions
on: [ push ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.17.0 ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build:prod
      - name: linting ts
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:style
      - name: unit tests
        run: npm run test:unit
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "storybook:build"

