name: GitHub Actions
run-name: ${{ github.actor }} runs GitHub actions
on: [ push ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-ui-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.10.0 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build project
        run: npm run build:prod
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "storybook:build"
          # Shouldn't be set for real project
          autoAcceptChanges: "main"

  lint-and-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.10.0 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: linting ts
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:style
      - name: unit tests
        run: npm run test:unit
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'reports'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Output Deployed URL
        run: echo "Deployed content is available at ${{ steps.checks.outputs.url }}"
